# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8066fc05f055b7dc038266e53c5c2f40"
name = "cart-transform-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "test-store-by-rasel.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
